### ISSUE TITLE
When app is opened, you don't see a carousel

### ISSUE THREAD

**Issue by bernaferrari** [SupahSoftware/AndroidExampleCarousel#1]
When app is opened, the adapter images are not in carousel size. Only after user touches the screen that onScrollListener is triggered.

**Comment by SupahSoftware** [comment]
Can you show me your adapter code? In your adapter, when you set your data,
are you calling 'notifyDatasetChanged' or something similar?

**Comment by bernaferrari** [comment]
Actually, this is happening with the sample

**Comment by SupahSoftware** [comment]
Can you explain a little bit further? I just wiped the GitHub repository
from my computer and re-cloned it, and everything seems fine on my end.

**Comment by bernaferrari** [comment]
Here, it only updates the view size after first scroll.
![bug](https://user-images.githubusercontent.com/351125/53065964-a04e0e00-34ac-11e9-9c26-aec2e55d3925.gif)

**Comment by SupahSoftware** [comment]
Did you pull down the GitHub repository exactly or did you follow the
Medium post or the YouTube video?

**Comment by bernaferrari** [comment]
I downloaded the archive from github, which should be the same as cloning.
Android Pie on S9.

**Comment by MohammedAlaaMorsi** [comment]
@SupahSoftware @bernaferrari , I had the same issue just put this code inside the HorizontalCarouselRecyclerView class
```kotlin
init {
        onScrollChanged()
      }
```

**Comment by SupahSoftware** [comment]
Closing this issue due to the solution above by @Mohammed-Alaa . Thanks for posting the update Mohammed! I'm curious as to why this is an issue for some people, and not for others tho. It seems like it could be a race condition, as it wasn't happening for me.

**Comment by bernaferrari** [comment]
Why didn't you update the code?

**Comment by SupahSoftware** [comment]
@bernaferrari Whoops. There was no pull request so I updated the code locally and forgot to push after my commit. When I get home tonight I'll push the changes up. Thanks for letting me know!
